### PR TITLE
🐛 Make dropdowns on catalog#index work properly

### PR DESCRIPTION
**Pull request by kirkkwang**
# Story

The bootstrap dropdown menu was not working properly and removing the require fixes the issue.  I think maybe something else that was also requiring it which caused a conflict.

# Screenshots / Video
image

### Ref:
  - https://github.com/samvera-labs/bulkrax/commit/b689afa637142437d802d2c137fcf2386bcb21c7

### CODE REVIEW

**Review by jeremyf — COMMENTED** [review]
My assumption is that prior to this change, were you to run the application locally, you'd see multiple declarations of the bootstrap JS script lines in the HTML.  As it, there are two references for this in the HTML document.

Then with this change, we'd only see that declaration once.

Is that the case?  I have slight trepidations about removing (especially if we didn't add it)

**Comment by jeremyf** [comment]
Further sleuthing, we introduced this https://github.com/scientist-softserv/west-virginia-university/commit/3e10fb1769539a59c8478354f390993f1fe83c60

**Comment by kirkkwang** [comment]
> Further sleuthing, we introduced this [3e10fb1](https://github.com/scientist-softserv/west-virginia-university/commit/3e10fb1769539a59c8478354f390993f1fe83c60)

Good find, I'm fine with keeping it in if it's supposed to be there, but what I'm observing is that even in a deployed environment such as here

https://congressarchivesdev.lib.wvu.edu/?utf8=%E2%9C%93&search_field=all_fields&q=

I'm unable to click on the dropdown so something is broken both locally and deployed.  I'm definitely opened to other suggestions.

**Comment by ShanaLMoore** [comment]
How do the bulkrax fields perform with this change? Summer's commit shows that it was added for bulkrax.

**Comment by kirkkwang** [comment]
> How do the bulkrax fields perform with this change? Summer's commit shows that it was added for bulkrax.

Yeah looks like it doesn't work, so at the moment it's either the dropdown menus work or the Bulkrax tables work but not both, I'll play with the requires to see if there's something else we need

**Comment by kirkkwang** [comment]
@jeremyf @ShanaLMoore I updated Bulkrax to add javascript to make the tabs work.  Ultimately I think we should remove bootstrap because we introduced specifically for Bulkrax and thus I think the fix should be in Bulkrax and not this application.

**Review by jeremyf — APPROVED** [review]

**Pull request merged**
